name: Production Deploy

on:
  push:
    branches:
      - 'production'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t joelkb-dev .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to Digital Ocean Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run:
          docker tag joelkb-dev registry.digitalocean.com/e11/joelkb-dev
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/e11/joelkb-dev